plugins {
	id 'java'
	id("org.springframework.boot") version "3.4.0"
	id("io.spring.dependency-management") version "1.1.6"
}
group = 'com.accenture.mercury'
version = '4.1.0'

description = 'Parent Mercury'


repositories {
	mavenCentral()
	mavenLocal()
}

dependencies {
	configurations.configureEach {
		exclude module: 'log4j-to-slf4j'
		exclude module: 'logback-classic'
	}
	implementation 'org.mongodb:mongodb-driver-reactivestreams:4.11.1'
	implementation 'org.mongodb:mongodb-driver-core:4.11.1'
	implementation 'org.mongodb:bson:4.11.1'
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb-reactive'

	implementation 'org.springframework.boot:spring-boot-starter-web'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	implementation("org.platformlambda:event-script-engine:4.1.2")
	testImplementation platform('org.junit:junit-bom:5.10.0')
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
